apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-isnr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-isnr
    app.kubernetes.io/part-of: test-app-lael
  name: test-component-isnr
  namespace: build-e2e-isps-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-isnr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-isnr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:94094341c4790521f31c71856330c52b45bdb0d96dc50768612ddeb1209cc8b6
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
