apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-isnr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-isnr
    app.kubernetes.io/part-of: test-app-lael
  name: test-component-isnr
  namespace: build-e2e-isps-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: test-component-isnr
    weight: null
status: {}
